sudo: required
dist: trusty

language: java
  
os:
  - linux
  
jdk:
  - oraclejdk8 # used by maven runtime

cache:
  directories:
  - $HOME/.m2/repository
before_cache:
  - rm -rf $HOME/.m2/repository/net/sf/oval

install:
  - ls -l /usr/lib/jvm/

script: mvn clean verify -t .travis_toolchains.xml